version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_portfolio
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: