# Generated by Django 5.2.1 on 2025-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_user_id_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repo_url',
        ),
        migrations.AddField(
            model_name='project',
            name='delayAnimation',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='modalDetails',
            field=models.JSONField(default=list),
        ),
    ]
