FROM python:3.11-slim

WORKDIR /app

# Instala cliente de PostgreSQL + dependencias necesarias
RUN apt-get update && apt-get install -y postgresql-client build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]