# Generated by Django 5.2.1 on 2025-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_clicks_link_is_active_link_order_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
